name: flutter_acrcloud
description: A Flutter plugin for the ACRCloud music recognition API. This plugin provides a simple interface for using ACRCloud to recognize music from the device's microphone.
version: 1.0.0
homepage: https://github.com/nrubin29/flutter_acrcloud

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation:

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  json_serializable:

flutter:
  plugin:
    platforms:
      android:
        package: com.nrubintech.flutter_acrcloud
        pluginClass: FlutterAcrcloudPlugin
      ios:
        pluginClass: FlutterAcrcloudPlugin
